get breakpoints shots implementation into page mode
lost-pixel/lost-pixel pull request #255
Opened 2023-04-02 09:34 UTC by d-ivashchuk

2023-04-04 12:51 UTC, chriskalmar requested changes

2023-04-04 12:51 UTC, chriskalmar commented on examples/example-ladle/build/assets/axe.2fd54cbc.js
This looks like a build asset.

2023-04-04 12:51 UTC, chriskalmar commented on src/shots/shots.ts
Could we include the breakpoint (if provided) in this log?
```
`Taking screenshot of '${shotItem.shotName}'`,
```

2023-08-08 13:26 UTC, b3nThomas commented
Hello there. Apologies if me commenting here is inappropriate, but any updates on this PR?
This feature would be very positively welcomed 🙂

2023-08-08 17:37 UTC, d-ivashchuk commented
You can already use the feature in an experimental build 😀

```js
module.exports = {
  storybookShots: {
    storybookUrl: './storybook-static',
    breakpoints: [640, 1024],
  },
  lostPixelProjectId: 'xllx',
  apiKey: process.env.LOST_PIXEL_API_KEY,
};
```

`uses: lost-pixel/lost-pixel@feature/breakpoint-shots`

So far we are not merging it and gathering the feedback!

2023-09-17 19:08 UTC, merged