Feature/ladle integration
lost-pixel/lost-pixel pull request #89
Opened 2022-07-21 17:07 UTC by d-ivashchuk

2022-07-23 19:39 UTC, d-ivashchuk commented on src/config.ts
> +     * URL of the Storybook instance or local folder
```suggestion
     * URL of the Ladle served instance
```

2022-07-24 10:39 UTC, chriskalmar requested changes

2022-07-24 10:39 UTC, chriskalmar commented on src/createShots.ts
> +      throw error;
If we are not doing anything with the caught error (e.g. log it) we might also just skip the try-catch block altogether.

2022-07-24 11:18 UTC, chriskalmar approved these changes

2022-07-24 11:18 UTC, merged